---
# tasks file for wp.firewalld
- name: firewalld
  package:
    name: firewalld
    state: present
  tags: firewalld


- name: permit traffic on port 8080
  firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled
  tags: firewalld
