---
# tasks file for wp.import_image
##########"recupération image"

#idemptotence check image
# - name: checking for pre-existing package_image
#   command: ls "{{ project_dir }}/MWC_01.00.00_install/images/DevOps.png"
#   register: skip_unpack_image
#   ignore_errors: true
#   changed_when: false
#   tags: image

- name: Extract dump_image.tar.gz > DevOps.png
  unarchive:
    src: "{{ livr_dir }}/INPUT/PACKAGE/dump_image.tar.gz"
    dest: "{{ livr_dir }}/INPUT/PACKAGE/"
    mode: 0755
    owner: wmcuser
    remote_src: yes
    creates: "{{ project_dir }}/MWC_01.00.00_install/images/2/21/DevOps.png"
  # when: skip_unpack_image.rc > 0
  tags: image

- name : importImages.php
  command:
    cmd: "php {{ project_dir }}/MWC_01.00.00_install/maintenance/importImages.php --dbuser=WIKI_DB_USER --dbpass={{ mdp_bdd }} {{ livr_dir }}/INPUT/PACKAGE/images/"
    creates: "{{ project_dir }}/MWC_01.00.00_install/images/2/21/DevOps.png"
  tags: image

- name : rebuildrecentchanges.php
  command: "php {{ project_dir }}/MWC_01.00.00_install/maintenance/rebuildrecentchanges.php"
  tags: image
