---
  ###installation FS
- name: display setup
  debug:
    var: ansible_mounts
    verbosity: 1
  tags: filesystem

- name: Check if {{ mysql_data_dir }} is already a mountpoint
  set_fact:
    mysql_data_dir_mounted: "{% for mounts in ansible_mounts %}{% if mounts.mount == mysql_data_dir %}true{% endif %}{% endfor %}"
  tags: filesystem

- name: display setup
  debug:
    var: mysql_data_dir_mounted
    verbosity: 1
  tags: FS

- name: install xfs tools
  apt:
    name: xfsprogs
    state: present
  tags: filesystem

- name: Create a xfs filesystem on {{ log_disk }} to store system logs
  filesystem:
    fstype: xfs
    dev: "{{ log_disk }}"
  tags: filesystem

- name: mount {{ log_disk }} on /var/log
  mount:
    src: "{{ log_disk }}"
    path: /var/log
    state: mounted
    fstype: xfs
  tags: filesystem

- name: Create a xfs filesystem on {{ data_disk }} to store MySQL data
  filesystem:
    fstype: xfs
    dev: "{{ data_disk }}"# tasks file for wp.creation_FS
  tags: filesystem



# tasks file for wp.install_maria_DB
- name: install MariaDB
  apt:
    name: mariadb-server
    state: present
  tags: mariadb

- block:
  - name: mount {{ data_disk }} on /mnt
    mount:
      src: "{{ data_disk }}"
      path: /mnt
      state: mounted
      fstype: xfs
    tags: mariadb

  - name: stop MariaDB
    systemd:
      name: mariadb
      state: stopped
    tags: mariadb

  - name: copy original database
    copy:
      src: /var/lib/mysql/
      dest: /mnt
      owner: mysql
      group: mysql
      remote_src: yes
    tags: mariadb

  - name: unmount {{ data_disk }} from /mnt
    mount:
      src: "{{ data_disk }}"
      path: /mnt
      state: absent
    tags: mariadb

  - name: mount {{ data_disk }} on /var/lib/mysql
    mount:
      src: "{{ data_disk }}"
      path: /var/lib/mysql
      state: mounted
      fstype: xfs
    tags: mariadb

  - name: change permissions on /var/lib/mysql
    file:
      path: /var/lib/mysql
      state: directory
      owner: mysql
      group: mysql
    tags: mariadb
  when: not mysql_data_dir_mounted


- name: start MariaDB on boot
  systemd:
    name: mariadb
    state: started
    enabled: yes
  tags: mariadb
