---
# tasks file for wp.installmediawiki

#idemptotence check localSetting.php
#- name: checking for pre-existing LocalSettings
#  command: cat "{{ project_dir }}/MWC_01.00.00_install/LocalSettings.php"
#  register: skip_install
#  ignore_errors: true
#  changed_when: false

###### PHP.install

- name: Installing mediawiki
  command:
    cmd: "php {{ project_dir }}/MWC_01.00.00_install/maintenance/install.php --dbuser=WIKI_DB_USER --dbpass=WIKI_DB_PASSWD --dbname=WIKI_DB --dbserver=localhost --dbtype=mysql --scriptpath=/MWC_01.00.00_install --confpath={{ project_dir }}/MWC_01.00.00_install  --server='http://192.168.56.110' --lang=fr --pass='{{ mdp_connexion_wm }}' superwiki admin"
    creates: "php {{ project_dir }}/MWC_01.00.00_install/LocalSettings.php"
#  when: skip_install.rc > 0

####data###

  ###recupération de donnees.xml

- name: Import donnnees.xml
  command:
    cmd: "php {{ project_dir }}/MWC_01.00.00_install/maintenance/importDump.php --dbuser=WIKI_DB_USER --dbpass={{ mdp_bdd }} /appli/mediawiki/LIVR/28-05/INPUT/PACKAGE/Donnees.xml"
    #when: skip_donnees.rc > 0

- name : rebuildrecentchanges.php
  command: "php {{ project_dir }}/MWC_01.00.00_install/maintenance/rebuildrecentchanges.php"


##########"recupération image"

- name: Extract dump_image.tar.gz > DevOps.png
  unarchive:
    src: "{{ livr_dir }}/INPUT/PACKAGE/dump_image.tar.gz"
    dest: "{{ livr_dir }}/INPUT/PACKAGE/"
    mode: 0755
    owner: wmcuser
    remote_src: yes
    creates: "{{ project_dir }}/MWC_01.00.00_install/images/2/21/DevOps.png"


- name : importImages.php
  command:
    cmd: "php {{ project_dir }}/MWC_01.00.00_install/maintenance/importImages.php --dbuser=WIKI_DB_USER --dbpass={{ mdp_bdd }} {{ livr_dir }}/INPUT/PACKAGE/images/"
    creates: "{{ project_dir }}/MWC_01.00.00_install/images/2/21/DevOps.png"

- name : rebuildrecentchanges.php
  command:
    cmd: "php {{ project_dir }}/MWC_01.00.00_install/maintenance/rebuildrecentchanges.php"
    creates: "{{ project_dir }}/MWC_01.00.00_install/images/2/21/DevOps.png"


  #################LoGo

- name: Extract LoGo.tar.gz > GRC-135.png
  unarchive:
    src: "{{ livr_dir }}/INPUT/PACKAGE/LoGo.tar.gz"
    dest: "{{ project_dir }}/MWC_01.00.00_install/resources/assets"
    mode: 0755
    owner: wmcuser
    remote_src: yes
    creates: "{{ project_dir }}/MWC_01.00.00_install/ressources/assets/LoGo/GRC-135.png"
      # when: skip_unpack_image.rc > 0

- name: config setting.conf pour LOGO
  lineinfile:
    path: "{{ project_dir }}/MWC_01.00.00_install/LocalSettings.php"
    regexp: '1x'
    line: "$wgLogos = [ '1x' => \"$wgResourceBasePath/resources/assets/LoGo/GRC-135.png\" ];"

#Config apache2

- name: setting apache root dir to {{ project_dir }}
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: DocumentRoot
    line: " DocumentRoot {{ project_dir }}"

- name: adding directory to apache2.conf
  blockinfile:
    path: /etc/apache2/apache2.conf
    block: |
      <Directory /appli/projects/MWC/mediawiki>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
        Allow from all
      </Directory>
  notify: restart apache2



# - name: restart apache2
#   service:
#     name: apache2
#     state: restarted
#   tags: apache2
