---

- name: Installation Mediawiki
  become: true
  hosts: wordpress
  tasks:

#unzip
      - name: install unzip package
        package:
          name: unzip
          state: present

#livraison package
      - name: Creates directory LIVR
        file:
          path: /appli/mediawiki/LIVR/28-05
          state: directory

      #     #livraison package
      # - name: Creates directory test
      #   file:
      #     path: /tmp/testautorisation
      #     state: directory

      - name: Unzip input.zip
        unarchive:
          src: /tmp/INPUT.zip
          dest: /appli/mediawiki/LIVR/28-05
          remote_src: yes
          creates: /appli/mediawiki/LIVR/28-05/INPUT

#deversement des livrables
      - name: Creates directory projects/MWC/mediawiki
        file:
          path: /appli/projects/MWC/mediawiki
          state: directory

#-tar de mediawiki
      - name: Extract mediawiki.tar.gz > MWC-01.00.00_install
        unarchive:
          src: /appli/mediawiki/LIVR/28-05/INPUT/PACKAGE/wikidevops.tar.gz
          dest: /appli/projects/MWC/mediawiki
          remote_src: yes
          creates: /appli/projects/MWC/mediawiki/wikidevops

#renomage
      - name: renomage
        command: mv /appli/projects/MWC/mediawiki/wikidevops /appli/projects/MWC/mediawiki/MWC01.00.00install
#

#apt update_cache
      - name: apt update
        apt:
          update_cache: yes


#         - name: install apache and php7.3
#           apt:
#             name:
#         - apache2
#         - php
#         - php-mysql
#       state: present
#       update_cache: yes
#
#
#
# # DATABASE SERVER
#
# - hosts: db
#   become: true
#   vars_files: vars/main.yml
#   vars:
#     root_password: "......"
#
#   tasks:
#   - name: install mysql
#     apt:
#       name:
#         - mysql-server
#              state: present
#       update_cache: yes
#
#   - name: Create MySQL config
#     copy:
#       dest: "/root/.my.cnf"
#       content: |
#                user=root
#         password={{ root_password }}
