---

- name: Installation Mediawiki
  become: true
  hosts: wordpress
  tasks:

#unzip
      - name: install unzip package
        package:
          name: unzip
          state: present

#livraison package
      - name: Creates directory LIVR
        file:
          path: /appli/mediawiki/LIVR/28-05
          state: directory

      #     #livraison package
      # - name: Creates directory test
      #   file:
      #     path: /tmp/testautorisation
      #     state: directory

      - name: Unzip input.zip
        unarchive:
          src: /tmp/INPUT.zip
          dest: /appli/mediawiki/LIVR/28-05
          remote_src: yes
          creates: /appli/mediawiki/LIVR/28-05/INPUT

#deversement des livrables
      - name: Creates directory projects/MWC/mediawiki
        file:
          path: /appli/projects/MWC/mediawiki
          state: directory

#-tar de mediawiki
      - name: Extract mwikidevop.tar.gz >wikidevops
        unarchive:
          src: /appli/mediawiki/LIVR/28-05/INPUT/PACKAGE/wikidevops.tar.gz
          dest: /appli/projects/MWC/mediawiki
          remote_src: yes
          creates: /appli/projects/MWC/mediawiki/wikidevops

# #renomage
#       - name: renomage
#         command: mv /appli/projects/MWC/mediawiki/wikidevops "/appli/projects/MWC/mediawiki/MWC_01.00.00_install"
#         #creates: /appli/projects/MWC/mediawiki/

# #apt update_cache
#       - name: apt update
#         apt:
#           update_cache: yes


      - name: install php7.3
        package:
          name:
            - php
            - php-mysql
            - php-xml
            - php-mbstring
            - python3-mysqldb
          state: present
          update_cache: yes


      - name: install apache2
        package:
          name:
            - apache2
            - libapache2-mod-php
          state: present
          update_cache: yes

      - name: install MariaDB
        apt:
          name: mariadb-server
          state: present

      - name: start MariaDB on boot
        systemd:
          name: mariadb
          state: started
          enabled: yes

# DATABASE SERVER

#config


  #creare mediawiki Mysql database
      - name: create mediawiki mysql database
        mysql_db:
          name: WIKI_DB
          state: present

      - name: create mediawiki mysql
        mysql_user:
          name: WIKI_DB_USER
          host: localhost
          password: WIKI_DB_PASSWD
          priv: WIKI_DB.*:ALL


#   - name: Create MySQL config
#     copy:
#       dest: "/root/.my.cnf"
#       content: |
#                user=root
#         password={{ root_password }}

###### PHP.install

      # - name: Run a script with arguments (free form)
      #   script:
      #     cmd: /appli/projects/MWC/mediawiki/MWC_01.00.00_install/maintenance/install.php --dbuser=WIKI_DB_User --dbpass=WIKI_DB_PSSWD --dbname=WIKI_DB --dbserver=localhost --dbtype=mysql --scriptpath=/mediawiki/MWC_1.35.2_install --confpath=appli/projects/MWC/mediawiki/MWC_1.35.2_install  --server="http://192.168.56.110" --lang=fr --pass=azerty123!! superwiki admin
      #     remote_src: yes

      - name: run script
        shell: 'appli/projects/MWC/mediawiki/MWC_01.00.00_install/maintenance/install.php' --dbuser=WIKI_DB_USER --dbpass=WIKI_DB_PSSWD --dbname=WIKI_DB --dbserver=localhost --dbtype=mysql --scriptpath=/mediawiki/MWC_01.00.00_install --confpath=appli/projects/MWC/mediawiki/MWC_01.00.00_install'  --server="http://192.168.56.110" --lang=fr --pass=azerty123!! superwiki admin
