---

- name: Installation Mediawiki
  become: true
  hosts: vmcible
  vars:
    - livr_dir: /appli/mediawiki/LIVR/28-05
    - project_dir: /appli/projects/MWC/mediawiki
    - package_path: /tmp/INPUT.zip
  tasks:

#unzip
      - name: install unzip package
        package:
          name: unzip
          state: present

#livraison package
      - name: Creates directory LIVR
        file:
          path: "{{ livr_dir }}"
          state: directory

      - name: Unzip input.zip
        unarchive:
          src: "{{ package_path }}"
          dest: "{{ livr_dir }}"
          remote_src: yes
          creates: "{{ livr_dir }}/INPUT"

#deversement des livrables
      - name: Creates directory projects/MWC/mediawiki
        file:
          path: "{{ project_dir }}"
          state: directory

#idemptotence check
      - name: checking for pre-existing package
        command: ls "{{ project_dir }}/MWC_01.00.00_install"
        register: skip_unpack
        ignore_errors: true
        changed_when: false

#-tar de mediawiki
      - name: Extract wikidevop.tar.gz > wikidevops
        unarchive:
          src: "{{ livr_dir }}/INPUT/PACKAGE/wikidevops.tar.gz"
          dest: "{{ project_dir }}"
          mode: 0755
          owner: wmcuser
          remote_src: yes
          creates: "{{ project_dir }}/wikidevops"
        when: skip_unpack.rc > 0

# #renaming
      - name: renaming
        command: mv "{{ project_dir }}/wikidevops" "{{ project_dir }}/MWC_01.00.00_install"
        when: skip_unpack.rc > 0
            #creates: "{{ project_dir }}"

# #apt update_cache
#       - name: apt update
#         apt:
#           update_cache: yes

      - name: install php7.3
        package:
          name:
            - php
            - php-mysql
            - php-xml
            - php-mbstring
            - python3-mysqldb
          state: present
          update_cache: yes

      - name: install apache2
        package:
          name:
            - apache2
            - libapache2-mod-php
          state: present
          update_cache: yes

      - name: install MariaDB
        apt:
          name: mariadb-server
          state: present

      - name: start MariaDB on boot
        systemd:
          name: mariadb
          state: started
          enabled: yes

# DATABASE SERVER

#config


  #creare mediawiki Mysql database
      - name: create mediawiki mysql database
        mysql_db:
          name: WIKI_DB
          state: present

      - name: create mediawiki mysql User
        mysql_user:
          name: WIKI_DB_USER
          host: localhost
          password: WIKI_DB_PASSWD
          priv: WIKI_DB.*:ALL


#   - name: Create MySQL config
#     copy:
#       dest: "/root/.my.cnf"
#       content: |
#                user=root
#         password={{ root_password }}

#idemptotence check localSetting.php
      - name: checking for pre-existing LocalSettings
        command: cat "{{ project_dir }}/MWC_01.00.00_install/LocalSettings.php"
        register: skip_install
        ignore_errors: true
        changed_when: false

###### PHP.install

      - name: Installing mediawiki
        command: "php /appli/projects/MWC/mediawiki/MWC_01.00.00_install/maintenance/install.php --dbuser=WIKI_DB_USER --dbpass=WIKI_DB_PASSWD --dbname=WIKI_DB --dbserver=localhost --dbtype=mysql --scriptpath=/MWC_01.00.00_install --confpath={{ project_dir }}/MWC_01.00.00_install  --server='http://192.168.56.110' --lang=fr --pass='azerty123!!' superwiki admin"
        when: skip_install.rc > 0

###Config apache2


      - name: setting apache root dir to {{ project_dir }}
        lineinfile:
          path: /etc/apache2/sites-available/000-default.conf
          regexp: DocumentRoot
          line: " DocumentRoot {{ project_dir }}"


      - name: checking apache2.conf
        command: grep -Fq "{{ project_dir }}" /etc/apache2/apache2.conf
        register: skip_a2conf
        ignore_errors: true
        changed_when: false

      - name: adding directory to apache2.conf
        blockinfile:
          path: /etc/apache2/apache2.conf
          block: |
            <Directory /appli/projects/MWC/mediawiki>
              Options Indexes FollowSymLinks
              AllowOverride None
              Require all granted
              Allow from all
            </Directory>
        when: skip_a2conf.rc > 0


      - name: config apache2 - 000-default.conf
        ansible.builtin.lineinfile:
            path: /etc/apache2/sites-available/000-default.conf
            regexp: DocumentRoot
            line: " DocumentRoot {{ project_dir }}"



      - name: restart apache2
        service:
          name: apache2
          state: restarted
  ###recupération des donnees.xml

# ###"idemptotence check donnnes.xml"
#       - name: checking for pre-existing donnees.xml
#         command: cat "{{ project_dir }}/MWC_01.00.00_install/    "
#         register: skip_donnees
#         ignore_errors: true
#         changed_when: false

      - name: Import donnnees.xml
        command: "php {{ project_dir }}/MWC_01.00.00_install/maintenance/importDump.php --dbuser=WIKI_DB_USER --dbpass=WIKI_DB_PASSWD /appli/mediawiki/LIVR/28-05/INPUT/PACKAGE/Donnees.xml"
        #when: skip_donnees.rc > 0

      - name : rebuildrecentchanges.php
        command: "php {{ project_dir }}/MWC_01.00.00_install/maintenance/rebuildrecentchanges.php"


##########"recupération image"

#idemptotence check image
      - name: checking for pre-existing package_image
        command: ls "{{ project_dir }}/MWC_01.00.00_install/images/DevOps.png"
        register: skip_unpack_image
        ignore_errors: true
        changed_when: false

      - name: Extract dump_image.tar.gz > DevOps.png
        unarchive:
          src: "{{ livr_dir }}/INPUT/PACKAGE/dump_image.tar.gz"
          dest: "{{ project_dir }}/MWC_01.00.00_install/"
          mode: 0755
          owner: wmcuser
          remote_src: yes
          creates: "{{ project_dir }}/MWC_01.00.00_install/images/DevOps.png"
        when: skip_unpack_image.rc > 0

      - name : importImages.php
        command: "php {{ project_dir }}/MWC_01.00.00_install/maintenance/importImages.php --dbuser=WIKI_DB_USER --dbpass=WIKI_DB_PASSWD {{ project_dir }}/MWC_01.00.00_Install/images/"

      - name : rebuildrecentchanges.php
        command: "php {{ project_dir }}/MWC_01.00.00_install/maintenance/rebuildrecentchanges.php"
####LOGO
#impotence du logo
# - name: checking for pre-existing packkage logo
#   command: ls "{{ project_dir }}/MWC_01.00.00_install/images/DevOps.png"
#   register: skip_unpack_image
#   ignore_errors: true
#   changed_when: false

      - name: Extract LoGo.tar.gz > GRC-135.png
        unarchive:
          src: "{{ livr_dir }}/INPUT/PACKAGE/LoGo.tar.gz"
          dest: "{{ project_dir }}/MWC_01.00.00_install/resources/assets"
          mode: 0755
          owner: wmcuser
          remote_src: yes
          creates: "{{ project_dir }}/MWC_01.00.00_install/ressources/assets/LoGo/GRC-135.png"
        # when: skip_unpack_image.rc > 0

      - name: config setting.conf pour LOGO
        lineinfile:
          path: {{ project_dir }}/MWC_01.00.00_install/LocalSettings.php
          regexp: '1x'
          line: "$wgLogos = [ '1x' => \"$wgResourceBasePath/resources/assets/LoGo/GRC-135.png\" ];"
      # - name: renaming
      #   command: mv "{{ project_dir }}/wikidevops" "{{ project_dir }}/MWC_01.00.00_install"
      #   when: skip_unpack.rc > 0
