---

- name: Installation Mediawiki
  become: true
  hosts: vmcible
  vars:
    - livr_dir: /appli/mediawiki/LIVR/28-05
    - project_dir: /appli/projects/MWC/mediawiki
  tasks:

#unzip
      - name: install unzip package
        package:
          name: unzip
          state: present

#livraison package
      - name: Creates directory LIVR
        file:
          path: "{{ livr_dir }}"
          state: directory

      - name: Unzip input.zip
        unarchive:
          src: /tmp/INPUT.zip
          dest: "{{ livr_dir }}"
          remote_src: yes
          creates: "{{ livr_dir }}/INPUT"

#deversement des livrables
      - name: Creates directory projects/MWC/mediawiki
        file:
          path: "{{ project_dir }}"
          state: directory

#-tar de mediawiki
      - name: Extract mwikidevop.tar.gz >wikidevops
        unarchive:
          src: "{{ livr_dir }}/INPUT/PACKAGE/wikidevops.tar.gz"
          dest: "{{ project_dir }}"
          remote_src: yes
          creates: "{{ project_dir }}/wikidevops"

# #renaming
#       - name: renaming
#         command: mv "{{ project_dir }}/wikidevops" "{{ project_dir }}/MWC_01.00.00_install"
#         #creates: "{{ project_dir }}"

# #apt update_cache
#       - name: apt update
#         apt:
#           update_cache: yes

      - name: install php7.3
        package:
          name:
            - php
            - php-mysql
            - php-xml
            - php-mbstring
            - python3-mysqldb
          state: present
          update_cache: yes


      - name: install apache2
        package:
          name:
            - apache2
            - libapache2-mod-php
          state: present
          update_cache: yes

      - name: install MariaDB
        apt:
          name: mariadb-server
          state: present

      - name: start MariaDB on boot
        systemd:
          name: mariadb
          state: started
          enabled: yes

# DATABASE SERVER

#config


  #creare mediawiki Mysql database
      - name: create mediawiki mysql database
        mysql_db:
          name: WIKI_DB
          state: present

      - name: create mediawiki mysql
        mysql_user:
          name: WIKI_DB_USER
          host: localhost
          password: WIKI_DB_PASSWD
          priv: WIKI_DB.*:ALL


#   - name: Create MySQL config
#     copy:
#       dest: "/root/.my.cnf"
#       content: |
#                user=root
#         password={{ root_password }}

###### PHP.install

      # - name: Run a script with arguments (free form)
      #   script:
      #     cmd: /appli/projects/MWC/mediawiki/MWC_01.00.00_install/maintenance/install.php --dbuser=WIKI_DB_User --dbpass=WIKI_DB_PSSWD --dbname=WIKI_DB --dbserver=localhost --dbtype=mysql --scriptpath=/mediawiki/MWC_1.35.2_install --confpath=appli/projects/MWC/mediawiki/MWC_1.35.2_install  --server="http://192.168.56.110" --lang=fr --pass=azerty123!! superwiki admin
      #     remote_src: yes

      - name: run script install.php
        shell: "{{ project_dir }}/MWC_01.00.00_install/maintenance/install.php"
        args:
            --dbuser="WIKI_DB_USER"
            --dbpass="WIKI_DB_PASSWD"
            --dbname="WIKI_DB"
            --dbserver=localhost
            --dbtype=mysql
            --scriptpath="/mediawiki/MWC_01.00.00_install"
            --confpath="{{ project_dir }}/MWC_01.00.00_install"
            --server="http://192.168.56.110"
            --lang=fr
            --pass=azerty123!!
            superwiki
            admin
