---

- name: Installation Mediawiki
  become: true
  hosts: wordpress
  tasks:

#unzip
      - name: install unzip package
        package:
          name: unzip
          state: present

#livraison package
      - name: Creates directory LIVR
        file:
          path: /appli/mediawiki/LIVR/28-05
          state: directory

      #     #livraison package
      # - name: Creates directory test
      #   file:
      #     path: /tmp/testautorisation
      #     state: directory

      - name: Unzip input.zip
        unarchive:
          src: /tmp/INPUT.zip
          dest: /appli/mediawiki/LIVR/28-05
          remote_src: yes
          creates: /appli/mediawiki/LIVR/28-05

#deversement des livrables
      - name: Creates directory projects/MWC/mediawiki
        file:
          path: /appli/projects/MWC/mediawiki
          state: directory

#-tar de mediawiki
      - name: Extract mediawiki.tar.gz
        unarchive:
          src: /appli/mediawiki/LIVR/28-05/INPUT/PACKAGE/wikidevops.tar.gz
          dest: /appli/projects/MWC/mediawiki/MWC_01.00.00_install
          remote_src: yes
          creates: /appli/projects/MWC/mediawiki/
