---

- name: Installation Mediawiki
  become: true
  hosts: wordpress
  tasks:

#unzip
      - name: install unzip package
        package:
          name: unzip
          state: present

#livraison package
      - name: Creates directory LIVR
        file:
          path: /appli/mediawiki/LIVR/28-05
          state: directory

      #     #livraison package
      # - name: Creates directory test
      #   file:
      #     path: /tmp/testautorisation
      #     state: directory

      - name: Unzip input.zip
        unarchive:
          src: /tmp/INPUT.zip
          dest: /appli/mediawiki/LIVR/28-05
          remote_src: yes
          creates: /appli/mediawiki/LIVR/28-05/INPUT

#deversement des livrables
      - name: Creates directory projects/MWC/mediawiki
        file:
          path: /appli/projects/MWC/mediawiki
          state: directory

#-tar de mediawiki
      - name: Extract mwikidevop.tar.gz >wikidevops
        unarchive:
          src: /appli/mediawiki/LIVR/28-05/INPUT/PACKAGE/wikidevops.tar.gz
          dest: /appli/projects/MWC/mediawiki
          remote_src: yes
          creates: /appli/projects/MWC/mediawiki/wikidevops

#renomage
      # - name: renomage
      #   command: mv /appli/projects/MWC/mediawiki/wikidevops /appli/projects/MWC/mediawiki/MWC01.00.00install
      #   creates: /appli/projects/MWC/mediawiki/MWC01.00.00install
#

# #apt update_cache
#       - name: apt update
#         apt:
#           update_cache: yes



      - name: install apache2 and php7.3 et modules comp
        package:
          name: "{{ item }}"
          update_cache: yes
          state: present
        Loop:
          - apache2
          - php
          - php-mysql
          - libapache2-mod-php
          - php-xml
          - php-mbstring
          #state: present
          #update_cache: yes

      - name: install python
        package:
          name: "{{ item }}"
          update_cahce: yes
          state: present
        Loop:
          - python3
          - python3-mysqldb


      - name: install MariaDB
        apt:
          name: mariadb-server
          state: present

      - name: start MariaDB on boot
        systemd:
          name: mariadb
          state: started
          enabled: yes

# DATABASE SERVER

      # - name: install mysql
      #   apt:
      #     name:
      #       - mysql-server
      #    state: present
      #    update_cache: yes

  #creare mediawiki Mysql database
      - name: create mediawiki mysql DATAbase
        mysql_db:
          name: WIKI_DB
          state: present

      - name: create mediawiki mysql
        mysql_user:
          name: WIKI_DB_USER
          host: localhost
          password: WIKI_DB_PASSWD
          priv: WIKI_DB.*:ALL


#   - name: Create MySQL config
#     copy:
#       dest: "/root/.my.cnf"
#       content: |
#                user=root
#         password={{ root_password }}
