---

- name: Installation Mediawiki
  become: true
  hosts: vmcible
  vars:
    - livr_dir: /appli/mediawiki/LIVR/28-05
    - project_dir: /appli/projects/MWC/mediawiki
  tasks:

#unzip
      - name: install unzip package
        package:
          name: unzip
          state: present

#livraison package
      - name: Creates directory LIVR
        file:
          path: "{{ livr_dir }}"
          state: directory

      - name: Unzip input.zip
        unarchive:
          src: /tmp/INPUT.zip
          dest: "{{ livr_dir }}"
          remote_src: yes
          creates: "{{ livr_dir }}/INPUT"

#deversement des livrables
      - name: Creates directory projects/MWC/mediawiki
        file:
          path: "{{ project_dir }}"
          state: directory

#idemptotence check
      - name: checking for existing pacakge
        command: ls "{{ project_dir }}/MWC_01.00.00_install"
        register: skip_unpack
        ignore_errors: true
        changed_when: false

#-tar de mediawiki
      - name: Extract wikidevop.tar.gz > wikidevops
        unarchive:
          src: "{{ livr_dir }}/INPUT/PACKAGE/wikidevops.tar.gz"
          dest: "{{ project_dir }}"
          mode: 0755
          owner: wmcuser
          remote_src: yes
          creates: "{{ project_dir }}/wikidevops"
        when: skip_unpack.rc > 0

# #renaming
      - name: renaming
        command: mv "{{ project_dir }}/wikidevops" "{{ project_dir }}/MWC_01.00.00_install"
        when: skip_unpack.rc > 0
            #creates: "{{ project_dir }}"

# #apt update_cache
#       - name: apt update
#         apt:
#           update_cache: yes

      - name: install php7.3
        package:
          name:
            - php
            - php-mysql
            - php-xml
            - php-mbstring
            - python3-mysqldb
          state: present
          update_cache: yes

      - name: install apache2
        package:
          name:
            - apache2
            - libapache2-mod-php
          state: present
          update_cache: yes

      - name: install MariaDB
        apt:
          name: mariadb-server
          state: present

      - name: start MariaDB on boot
        systemd:
          name: mariadb
          state: started
          enabled: yes

# DATABASE SERVER

#config


  #creare mediawiki Mysql database
      - name: create mediawiki mysql database
        mysql_db:
          name: WIKI_DB
          state: present

      - name: create mediawiki mysql User
        mysql_user:
          name: WIKI_DB_USER
          host: localhost
          password: WIKI_DB_PASSWD
          priv: WIKI_DB.*:ALL


#   - name: Create MySQL config
#     copy:
#       dest: "/root/.my.cnf"
#       content: |
#                user=root
#         password={{ root_password }}

###### PHP.install

      - name: Run a script with arguments (free form)
        command: "php /appli/projects/MWC/mediawiki/MWC_01.00.00_install/maintenance/install.php --dbuser=WIKI_DB_USER --dbpass=WIKI_DB_PASSWD --dbname=WIKI_DB --dbserver=localhost --dbtype=mysql --scriptpath=/MWC_01.00.00_install --confpath={{ project_dir }}/MWC_01.00.00_install  --server='http://192.168.56.110' --lang=fr --pass='azerty123!!' superwiki admin"


###Config apache2
      # - name: config apache2
      #   ansible.builtin.lineinfile:
      #       path: /etc/apache2/apache2.conf
      #       regexp: /var/www/html
      #       line: {{ project_dir }}

      - name: config apache2 -000defautl.conf
        ansible.builtin.lineinfile:
            path: /etc/apache2/site-available/000-default.conf
            regexp: /var/www/html
            line: "{{ project_dir }}"
