---
# tasks file for wp.prerequis
#unzip
- name: install unzip package
  package:
    name: unzip
    state: present


- name: install php7.3
  package:
    name:
      - php
      - php-mysql
      - php-xml
      - php-mbstring
      - python3-mysqldb
    state: present

- name: install apache2
  package:
    name:
      - apache2
      - libapache2-mod-php
    state: present

- name: firewalld
  package:
    name: firewalld
    state: present


- name: permit traffic on port 80
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
    immediate: yes
#  notify: restart firewalld
