---
# tasks file for wp.install_maria_DB
    - name: install MariaDB
      apt:
        name: mariadb-server
        state: present
     tags: mariadb

    - block:
        - name: mount {{ data_disk }} on /mnt
          mount:
            src: "{{ data_disk }}"
            path: /mnt
            state: mounted
            fstype: xfs
          tags: mariadb

        - name: stop MariaDB
          systemd:
            name: mariadb
            state: stopped
          tags: mariadb

        - name: copy original database
          copy:
            src: /var/lib/mysql/
            dest: /mnt
            owner: mysql
            group: mysql
            remote_src: yes
          tags: mariadb

        - name: unmount {{ data_disk }} from /mnt
          mount:
            src: "{{ data_disk }}"
            path: /mnt
            state: absent
          tags: mariadb

        - name: mount {{ data_disk }} on /var/lib/mysql
          mount:
            src: "{{ data_disk }}"
            path: /var/lib/mysql
            state: mounted
            fstype: xfs
          tags: mariadb

        - name: change permissions on /var/lib/mysql
          file:
            path: /var/lib/mysql
            state: directory
            owner: mysql
            group: mysql
      when: not mysql_data_dir_mounted
          tags: mariadb

    - name: start MariaDB on boot
      systemd:
        name: mariadb
        state: started
        enabled: yes
      tags: mariadb
