---
# tasks file for wp.prerequis
#unzip
- name: install unzip package
  package:
    name: unzip
    state: present


- name: install php7.3
  package:
    name:
      - php
      - php-mysql
      - php-xml
      - php-mbstring
      - python3-mysqldb
    state: present
    update_cache: yes

- name: install apache2
  package:
    name:
      - apache2
      - libapache2-mod-php
    state: present
    update_cache: yes

- name: install MariaDB
  apt:
    name: mariadb-server
    state: present

- name: start MariaDB on boot
  systemd:
    name: mariadb
    state: started
    enabled: yes
