---
# tasks file for wp.deversement
#livraison package
- name: Creates directory LIVR
  file:
    path: "{{ livr_dir }}"
    state: directory
  tags: deversement

- name: Unzip input.zip
  unarchive:
    src: "{{ package_path }}"
    dest: "{{ livr_dir }}"
    creates: "{{ livr_dir }}/INPUT"
  tags: deversement

#deversement des livrables
- name: Creates directory projects/MWC/mediawiki
  file:
    path: "{{ project_dir }}"
    state: directory
  tags: deversement

#idemptotence check
- name: checking for pre-existing package
  command: ls "{{ project_dir }}/MWC_01.00.00_install"
  register: skip_unpack
  ignore_errors: true
  changed_when: false
  tags: deversement

#-tar de mediawiki
- name: Extract wikidevop.tar.gz > wikidevops
  unarchive:
    src: "{{ livr_dir }}/INPUT/PACKAGE/wikidevops.tar.gz"
    dest: "{{ project_dir }}"
    mode: 0755
    owner: wmcuser
    remote_src: yes
    creates: "{{ project_dir }}/wikidevops"
  when: skip_unpack.rc > 0
  tags: deversement
# #renaming
- name: renaming
  command: mv "{{ project_dir }}/wikidevops" "{{ project_dir }}/MWC_01.00.00_install"
  when: skip_unpack.rc > 0
  tag: deversement 
