---
# tasks file for wp.deversement
#livraison package
- name: Creates directory LIVR
  file:
    path: "{{ livr_dir }}"
    state: directory

- name: Unzip input.zip
  unarchive:
    src: "{{ package_path }}"
    dest: "{{ livr_dir }}"
    creates: "{{ livr_dir }}/INPUT"

#deversement des livrables
- name: Creates directory projects/MWC/mediawiki
  file:
    path: "{{ project_dir }}"
    state: directory

#idemptotence check
#- name: checking for pre-existing package
#  command: ls "{{ project_dir }}/MWC_01.00.00_install"
#  register: skip_unpack
#  ignore_errors: true
#  changed_when: false

#-tar de mediawiki
- name: Extract wikidevop.tar.gz > wikidevops
  unarchive:
    src: "{{ livr_dir }}/INPUT/PACKAGE/wikidevops.tar.gz"
    dest: "{{ project_dir }}"
    mode: 0755
    owner: wmcuser
    remote_src: yes
    creates: "{{ project_dir }}/wikidevops"
#  when: skip_unpack.rc > 0

- name: renaming
  command:
    cmd: mv "{{ project_dir }}/wikidevops" "{{ project_dir }}/MWC_01.00.00_install"
    creates: "{{ project_dir }}/wikidevops"
#  when: skip_unpack.rc > 0

- name: create mediawiki mysql database
  mysql_db:
    name: WIKI_DB
    state: present
  tags: prerequis

- name: create mediawiki mysql User
  mysql_user:
    name: WIKI_DB_USER
    host: localhost
    password: "{{ mdp_bdd }}"
    priv: WIKI_DB.*:ALL
  tags: prerequis
