---
# tasks file for wp.installmediawiki
#idemptotence check localSetting.php
- name: checking for pre-existing LocalSettings
  command: cat "{{ project_dir }}/MWC_01.00.00_install/LocalSettings.php"
  register: skip_install
  ignore_errors: true
  changed_when: false

###### PHP.install

- name: Installing mediawiki
  command: "php /appli/projects/MWC/mediawiki/MWC_01.00.00_install/maintenance/install.php --dbuser=WIKI_DB_USER --dbpass=WIKI_DB_PASSWD --dbname=WIKI_DB --dbserver=localhost --dbtype=mysql --scriptpath=/MWC_01.00.00_install --confpath={{ project_dir }}/MWC_01.00.00_install  --server='http://192.168.56.110' --lang=fr --pass='azerty123!!' superwiki admin"
  when: skip_install.rc > 0
