---
# tasks file for wp.import_donnees.xml
  ###recupération des donnees.xml

- name: Import donnnees.xml
  command:
    cmd: "php {{ project_dir }}/MWC_01.00.00_install/maintenance/importDump.php --dbuser=WIKI_DB_USER --dbpass={{ mdp_bdd }} /appli/mediawiki/LIVR/28-05/INPUT/PACKAGE/Donnees.xml"
    #when: skip_donnees.rc > 0
  tags: importdata

- name : rebuildrecentchanges.php
  command: "php {{ project_dir }}/MWC_01.00.00_install/maintenance/rebuildrecentchanges.php"
  tags: importdata


### image #######################################""
##########"recupération image"

- name: Extract dump_image.tar.gz > DevOps.png
  unarchive:
    src: "{{ livr_dir }}/INPUT/PACKAGE/dump_image.tar.gz"
    dest: "{{ livr_dir }}/INPUT/PACKAGE/"
    mode: 0755
    owner: wmcuser
    remote_src: yes
    creates: "{{ project_dir }}/MWC_01.00.00_install/images/2/21/DevOps.png"
    register: need_to_import
  tags: importdata


- name : importImages.php
  command:
    cmd: "php {{ project_dir }}/MWC_01.00.00_install/maintenance/importImages.php --dbuser=WIKI_DB_USER --dbpass={{ mdp_bdd }} {{ livr_dir }}/INPUT/PACKAGE/images/"
    creates: "{{ project_dir }}/MWC_01.00.00_install/images/2/21/DevOps.png"
  when: need_to_import != 1
  tags: importdata

- name : rebuildrecentchanges.php
  command:
    cmd: "php {{ project_dir }}/MWC_01.00.00_install/maintenance/rebuildrecentchanges.php"
    creates: "{{ project_dir }}/MWC_01.00.00_install/images/2/21/DevOps.png"
  when: need_to_import != 1
  tags: importdata



  #################LoGo


  # tasks file for wp.import_logo
  ###LOGO

- name: Extract LoGo.tar.gz > GRC-135.png
  unarchive:
    src: "{{ livr_dir }}/INPUT/PACKAGE/LoGo.tar.gz"
    dest: "{{ project_dir }}/MWC_01.00.00_install/resources/assets"
    mode: 0755
    owner: wmcuser
    remote_src: yes
    creates: "{{ project_dir }}/MWC_01.00.00_install/ressources/assets/LoGo/GRC-135.png"
      # when: skip_unpack_image.rc > 0
  tags: importdata

- name: config setting.conf pour LOGO
  lineinfile:
    path: "{{ project_dir }}/MWC_01.00.00_install/LocalSettings.php"
    regexp: '1x'
    line: "$wgLogos = [ '1x' => \"$wgResourceBasePath/resources/assets/LoGo/GRC-135.png\" ];"
  tags: importdata
