---
- name: display setup
  debug:
    var: ansible_mounts
    verbosity: 1

- name: Check if {{ mysql_data_dir }} is already a mountpoint
  set_fact:
    mysql_data_dir_mounted: "{% for mounts in ansible_mounts %}{% if mounts.mount == mysql_data_dir %}true{% endif %}{% endfor %}"

- name: display setup
  debug:
    var: mysql_data_dir_mounted
    verbosity: 1

- name: install xfs tools
  apt:
    name: xfsprogs
    state: present

- name: Create a xfs filesystem on {{ log_disk }} to store system logs
  filesystem:
    fstype: xfs
    dev: "{{ log_disk }}"

- name: mount {{ log_disk }} on /var/log
  mount:
    src: "{{ log_disk }}"
    path: /var/log
    state: mounted
    fstype: xfs

- name: Create a xfs filesystem on {{ data_disk }} to store MySQL data
  filesystem:
    fstype: xfs
    dev: "{{ data_disk }}"# tasks file for wp.creation_FS
